### ISSUE TITLE
Pip install failing with setup.py not able to find requirements.txt

### ISSUE THREAD

**Issue by sandeepnmenon** [paperswithcode/galai#24]
I followed very simple install steps in my miniconda environment in my ubuntu 22.04
```
conda create --name galai
# Python version: 3.10.6
pip install galai
```
I am getting the following error
```
Defaulting to user installation because normal site-packages is not writeable
Collecting galai
  Using cached galai-1.0.1.tar.gz (22 kB)
  Preparing metadata (setup.py) ... done
Collecting accelerate
  Using cached accelerate-0.14.0-py3-none-any.whl (175 kB)
Collecting bert-score
  Using cached bert_score-0.3.12-py3-none-any.whl (60 kB)
Collecting datasets
  Using cached datasets-2.7.0-py3-none-any.whl (451 kB)
Requirement already satisfied: more_itertools in /usr/lib/python3/dist-packages (from galai) (8.10.0)
Collecting nltk
  Using cached nltk-3.7-py3-none-any.whl (1.5 MB)
Collecting openai
  Using cached openai-0.25.0.tar.gz (44 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting parallelformers
  Using cached parallelformers-1.2.7.tar.gz (48 kB)
  Preparing metadata (setup.py) ... done
Collecting prompt_toolkit
  Using cached prompt_toolkit-3.0.32-py3-none-any.whl (382 kB)
Collecting galai
  Using cached galai-1.0.0.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-k_x7j7ch/galai_f9ad4fa1673448a1aee54d93e0792767/setup.py", line 16, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by sandeepnmenon** [comment]
My Mistake.
Requires python version <3.10
