### ISSUE TITLE
Can't install python package

### ISSUE THREAD

**Issue by artyaaaa** [paperswithcode/galai#48]
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/x8/l933jg8d5477w13l2z3s2nkc0000gn/T/pip-install-nbosimmo/galai_56ef70c550314d5a8e3a62c7d3b02310/setup.py", line 16, in <module>
          with open("requirements.txt", "r") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

I've tried to create a requirements.txt file with pip freeze but nothing changed

**Comment by sho9029** [comment]
This package currently supports up to Python 3.9.
So if you are using 3.10 or higher, an error will occur.

**Comment by mkardas** [comment]
Hi all, as of galai version 1.1.0 it should work with python 3.10 without an issue.
