### ISSUE TITLE
Galai import failing after 1.1.0 update

### ISSUE THREAD

**Issue by lucasiq** [paperswithcode/galai#59]
I recently updated to galai 1.1.0, and now I can't go past import:

`>>> import galai as gal`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\galai\__init__.py", line 3, in <module>
    from galai.model import Model
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\galai\model.py", line 11, in <module>
    from galai.utils import escape_custom_split_sequence
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\galai\utils.py", line 66, in <module>
    @dataclass
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\galai\utils.py", line 116, in ModelInfo
    def all() -> list["ModelInfo"]:
TypeError: 'type' object is not subscriptable`

After that, I have tried reinstalling transformers, accelerate, tokenizers, and huggingface-hub, but nothing worked so far.

Thank you for your time

**Comment by mkardas** [comment]
Thanks @lucasiq for providing the stack trace, the problem was a type annotation not compatible with python 3.7. galai==1.1.2 should fix the issue.

**Comment by lucasiq** [comment]
> Thanks @lucasiq for providing the stack trace, the problem was a type annotation not compatible with python 3.7. galai==1.1.2 should fix the issue.

Thank you for your answer. I have updated it, but now I'm running this basic example:

`import galai as gal

model = gal.load_model("standard")
model.generate("Scaled dot product attention:\n\n\\[")`

and I'm getting this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\galai\__init__.py", line 124, in load_model
    model._load_checkpoint(checkpoint_path=hf_model)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\galai\model.py", line 114, in _load_checkpoint
    max_memory=max_memory,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_utils.py", line 2406, in from_pretrained
    dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
TypeError: dispatch_model() got an unexpected keyword argument 'offload_index'`
